### PR TITLE
fix: Remove references to deprecated io/ioutil pkg

### LINKED ISSUE #2806: refactor: remove refs to deprecated io/ioutil
Currently kaniko has some references to the deprecated io/ioutil library.  These should be replaced w/ `io` references (eg: s/ `io/ioutil` /`io`)

This abandoned PR attempted the fix but had some compilation issues:
https://github.com/GoogleContainerTools/kaniko/pull/2716

### PR DESCRIPTION
**Pull request by Manish-Giri**
Fixes #2806

**Description**

1. Replaced all functions from the deprecated `io/ioutil` pkg with the corresponding functions from other packages.
2. Did not make any changes to the contents of the `vendor` directory.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
Examples of user facing changes:
- kaniko adds a new flag `--registry-repo` to override registry

```

### CODE REVIEW

File: pkg/commands/copy_test.go [hunk 1]
```diff
@@ -121,6 +120,24 @@ func setupTestTemp(t *testing.T) string {
 	return tempDir
 }
 
+func readDirectory(dirName string) ([]fs.FileInfo, error) {
```
Comment (aaron-prindle) [inline pkg/commands/copy_test.go:123]: Nice!

**Review by aaron-prindle — APPROVED** [review]
LGTM, thanks for the PR @Manish-Giri!
