### PR TITLE
hasher: hash security.capability attributes

### LINKED ISSUE #1851: Kaniko does not persist setcap side effects
**Actual behavior**
`setcap` command does not persist to the finalized image. Running `getcap` in the finalized image returns an empty result.

**Expected behavior**
`getcap` should return the newly attached capabilities

**To Reproduce**
1. Create a Dockerfile with the following:
```
FROM python:3.9.9-slim-buster AS python
RUN apt-get update && apt-get install --assume-yes libcap2-bin nmap
RUN setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip $(which nmap)
RUN echo $(getcap $(which nmap))
```
2. See that during the Kaniko build, the echo command indeed produces the desired result.
3. Running the resulted image (from loading the resulting .tar file) and running `getcap` produces empty output

**Additional Information**
Used Kaniko 1.7-debug, and tried all sorts of flags, including single-snapshot and --snapshotMode=full
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by zhouhaibing089**
Fixes #1851 

**Description**

In Dockerfile, if there is something like:

```
RUN setcap cap_net_raw=+ep /path/to/binary
```

kaniko won't detect that there is a change on file `/path/to/binary` and
thus discards this layer. This patch allows the hasher function to
actually look at `security.capability` extended attributes.

The function `Lgetxattr` uses https://github.com/moby/moby/blob/c72c1ca62cd20e74582a01b8a54a58ae7f646d4c/pkg/system/xattrs_linux.go#L8

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

```
default hahser (--snapshotMode=full) now hashes security.capability attribute 
```

### CODE REVIEW

**Comment by zhouhaibing089** [comment]
@imjasonh: Could you help take a look when you get a chance? Thanks~

File: pkg/util/util.go [hunk 1]
```diff
@@ -172,3 +177,28 @@ func Retry(operation retryFunc, retryCount int, initialDelayMilliseconds int) er
 
 	return err
 }
+
+func Lgetxattr(path string, attr string) ([]byte, error) {
```
Comment (imjasonh) [inline pkg/util/util.go:181]: It doesn't look like this function needs to be exported, can we rename to `lgetxattr` and add a comment?

I'd also love to have a test covering this behavior, since it's pretty inscrutable to me personally.

Comment (zhouhaibing089) [reply pkg/util/util.go:181]: Sure, I can add a comment there.

Regarding tests, I can take a look at how to write a test(either a unit test or e2e test). But if you have any pointers or suggestions, that'd be great.

**Review by imjasonh — APPROVED** [review]
