### PR TITLE
Fix #506 add option additional-whitelist

### LINKED ISSUE #506: Paths under /var/run ignored
**Actual behavior**
Directories and files created under /var/run do not exist in created image.

**Expected behavior**
All directories and files created in Dockerfile should exist in created image.

**To Reproduce**
Create directory /var/run/test in Dockerfile. Observe that /var/run/test doesn't exist in resulting image.

**Additional Information**
 - Dockerfile 
FROM debian
RUN mkdir -p /var/run/test

### LINKED ISSUE #704: Removed files re-appear when using cache
**Actual behavior**

Building a Dockerfile which deletes a file _initially_ produces an image without the file. But when re-built using the cache, the resulting image contains the file again.

**Expected behavior**

The deleted file should never be present in final images, regardless of whether cache was used.

**To Reproduce**

1. Build a simple Dockerfile that adds a file then removes it in a later step, using Kaniko, with caching enabled:

```
FROM alpine

RUN mkdir -p /some/dir/ && echo 'first' > /some/dir/first.txt

RUN rm /some/dir/first.txt
```

2. Pull the resulting image from your registry, and run `ls -la /some/dir` in a container using the image. Observe that the directory is empty:

```
$ docker pull my-registry/my/img:latest && docker run --rm my-registry/my/img:latest bin/sh -c "ls -la /some/dir"
latest: Pulling from my/img
921b31ab772b: Already exists
b4f1d0fd5c4c: Pull complete
f6d9b826d061: Pull complete
Digest: sha256:213ace2d10ba510eeeaefa90b255da5f48e87ff7577a560bbb262b9db1cd9945
Status: Downloaded newer image for my-registry/my/img:latest
my-registry/my/img:latest
total 8
drwxr-xr-x    1 root     root          4096 Jun 24 14:27 .
drwxr-xr-x    1 root     root          4096 Jun 24 14:27 ..
```

3. Re-build the image using Kaniko, exactly as before. Logs will show that cached layers are being used.

4. Re-pull the image, re-run a container to `ls` again. Observe that the file has re-appeared.

```
docker pull my-registry/my/img:latest && docker run --rm my-registry/my/img:latest bin/sh -c "ls -la /some/dir"
latest: Pulling from my/img
921b31ab772b: Already exists
bd7f0d50b1ce: Pull complete
7d792274c478: Pull complete
Digest: sha256:9adda5568544f015972d112a9de87829ee2f02c0f65871ca2c632b10201be096
Status: Downloaded newer image for my-registry/my/img:latest
my-registry/my/img:latest
total 12
drwxr-xr-x    1 root     root          4096 Jun 24 14:34 .
drwxr-xr-x    1 root     root          4096 Jun 24 14:34 ..
-rw-r--r--    1 root     root             6 Jun 24 14:34 first.txt
```

**Additional Information**

- Example Dockerfile above.
- Build context is empty/irrelevant.
- Tried various combinations of `ADD <file-from-context> <path>`, `ADD <archive-of-directory>.tar.gz /`, `COPY <file-from-context> <path>` and using `RUN` steps to manipulate the files (as in the example). All combinations show this behaviour.
- This behaviour has been seen with various other later steps after the deletion (fs-related stuff, non-FS things like `ENTRYPOINT` etc).
- Kaniko Image details:

```
$ docker inspect gcr.io/kaniko-project/executor:v0.10.0
[
    {
        "Id": "sha256:9000801241318d6c9b8c2b505974f22fd74c57e0adfdb09c98870aef4923bb65",
        "RepoTags": [
            "gcr.io/kaniko-project/executor:latest",
            "gcr.io/kaniko-project/executor:v0.10.0"
        ],
        "RepoDigests": [
            "gcr.io/kaniko-project/executor@sha256:78d44ec4e9cb5545d7f85c1924695c89503ded86a59f92c7ae658afa3cff5400"
        ],
        ...
```

I can see from logs that a whiteout file is being created as expected in the first (uncached) build. However, it looks like the whiteout is either not making it's way into the cached data, or isn't being honoured when the cache is used later?

Peeking inside docker's `overlay2` directory confirms the lack of a whiteout in 2nd img. Upper layer internals in 1st image, built *without* cache:

```
/ # ls -la /var/lib/docker/overlay2/596f011a6b72769df25c4bd64e247bcede1f08f43f72be21790fc5a347d43921/diff/some/dir
total 8
drwxr-xr-x    2 root     root          4096 Jun 24 14:27 .
drwxr-xr-x    3 root     root          4096 Jun 24 14:27 ..
c---------    1 root     root        0,   0 Jun 24 14:28 first.txt
```

Upper layer internals for 2nd image, built *with* cache:

```
/ # ls -la /var/lib/docker/overlay2/afd849e49a216c891156d60f0dc99e4a6eb5b2a59ece4ca4d75e3705df9edc9e/diff/some/dir
total 8
drwxr-xr-x    2 root     root          4096 Jun 24 14:34 .
drwxr-xr-x    3 root     root          4096 Jun 24 14:34 ..
```

This behaviour has been observed in multiple environments:

- Using Jenkins on Kubernetes in GCP (as per [official suggestion](https://cloud.google.com/solutions/jenkins-on-kubernetes-engine) & [example](https://github.com/jenkinsci/kubernetes-plugin/blob/kubernetes-1.14.5/examples/kaniko-declarative.groovy)), with gcr.io  as final img dest & a k8s-deployed docker registry for cache.
- On a mac, using Kaniko via docker, internal private registry as final img dest & locally-running registry for cache (for easy testing)

### PR DESCRIPTION
**Pull request by cvgw**
Fixes #506, #903 

**Description**

Add a new option additional-whitelist which defaults to a single entry, "/var/run". This will allow users to remove "/var/run" from the whitelist or retain the current behavior with no change.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
- add new flag to customize ignored directories
```

### CODE REVIEW

**Comment by cvgw** [comment]
So this is working without caching but it doesn't work with caching, I think because `/var/run` is actually a link to `/run` on a lot of machines. My cached image ends up with `/run/test-folder` buut not `/var/run/test-folder` similar to #915 and as a result I think this PR should be merged after that is fixed.

File: pkg/util/fs_util_test.go [hunk 1]
```diff
@@ -58,7 +58,6 @@ func Test_DetectFilesystemWhitelist(t *testing.T) {
 		{"/dev", false},
 		{"/dev/pts", false},
 		{"/sys", false},
-		{"/var/run", false},
```
Comment (tejal29) [inline pkg/util/fs_util_test.go]: This test is little confusing. Seems like we are testing 
- whitelist before `AddToWhitelist` 
- whitelist after `AddToWhitelist`

Can we break this into 2 tests or only one after `AddToWhitelist` should suffice.

Comment (tejal29) [reply pkg/util/fs_util_test.go]: Ideally, it would be great if we convert this to Test Table driven with test cases
- no addiional whitelists
- 1 additional whitelist
- 1 or more additional whitelist

File: cmd/executor/cmd/root.go [hunk 2]
```diff
@@ -73,6 +74,16 @@ var RootCmd = &cobra.Command{
 			if len(opts.Destinations) == 0 && opts.ImageNameDigestFile != "" {
 				return errors.New("You must provide --destination if setting ImageNameDigestFile")
 			}
+
+			if additionalWhitelist == nil {
+				additionalWhitelist = []string{
```
Comment (tejal29) [inline cmd/executor/cmd/root.go]: i think we should default this to empty string. 
if users want to remove `/var/run` then they would have to run kaniko as
`/kaniko/executor --additional-whitelist=""`  instead users who need it to whitelisted should explicitly specify it.

e.g. #903

Comment (cvgw) [reply cmd/executor/cmd/root.go]: >if users want to remove /var/run then they would have to run kaniko as
/kaniko/executor --additional-whitelist="" instead users who need it to whitelisted should explicitly specify it.

I'm not strongly opposed to that but it seems like it would be a pretty major and invisible change for users. I can imagine users who don't realize they need to explicit add `/var/run` having their build times dramatically increase.

I think defaulting it to the current behavior would be a better user experience and let people opt in. I can see how an empty string might be a better experience for new users though.

WDYT

**Comment by cvgw** [comment]
This should include a README update before merging. Probably makes sense to agree on the default behavior before documenting.

File: cmd/executor/cmd/root.go (hunk 2 above)
Comment (tejal29) [reply cmd/executor/cmd/root.go]: I also thought about being backward compatible for existing users. 
 But we want these users to eventually correct their pod config and explicitly add `/var/run` to `additional-whitelist`. 
I would want us to push them towards that direction. 
This is challenging for us especially since users don't have to change their image tag if they are pointing to `latest`

Maybe for a couple of releases we could add a visible Warning that `/var/run` needs to be explicitly whitelisted especially if their build times have increased. 
Also monitor slack closely.

WDYT?

**Comment by cvgw** [comment]
Ya, I think a clear warning and good communication should handle most of
our problems. Let's do that. I'll make the change here.

File: cmd/executor/cmd/root.go (hunk 2 above)
Comment (cvgw) [reply cmd/executor/cmd/root.go]: linking for history https://github.com/GoogleContainerTools/kaniko/pull/975#issuecomment-577847191

File: pkg/util/fs_util_test.go (hunk 1 above)
Comment (cvgw) [reply pkg/util/fs_util_test.go]: done :+1:

File: cmd/executor/cmd/root.go (hunk 2 above)
Comment (cvgw) [reply cmd/executor/cmd/root.go]: done :+1:

**Comment by helder-moreira** [comment]
@tejal29 this pull request just broke a lot of pipelines I currently manage. Here is the error:

```
error building image: error building stage: failed to get filesystem from image: error removing var/run to make way for new symlink: unlinkat /var/run/secrets/kubernetes.io/serviceaccount/..2020_01_25_01_10_27.560757320: read-only file system
```

**Comment by cvgw** [comment]
> @tejal29 this pull request just broke a lot of pipelines I currently manage. Here is the error:
> 
> ```
> error building image: error building stage: failed to get filesystem from image: error removing var/run to make way for new symlink: unlinkat /var/run/secrets/kubernetes.io/serviceaccount/..2020_01_25_01_10_27.560757320: read-only file system
> ```

@helder-moreira are you using tag `latest`? Might be worth specifying a specific release of Kaniko like `v0.16.0`. Also there is also an open issue you can add your info to https://github.com/GoogleContainerTools/kaniko/issues/1002

**Comment by helder-moreira** [comment]
@tejal29 Thanks. I have already moved to and older version.

I will follow that issue, thanks.

**Comment by tejal29** [comment]
@helder-moreira This PR has been merged but not released.

**Comment by helder-moreira** [comment]
@tejal29 Got it. I was using the `debug` tag. I have now moved to `debug-v0.16.0`. Thanks.

**Comment by tejal29** [comment]
Thanks @helder-moreira. The team wasn't aware debug tag was updated on every push to master. Sorry for breaking your workflow. We will investigate and fix this soon.
