### PR TITLE
Fix #942 COPY or ADD to symlink destination breaks image

### LINKED ISSUE #942: ADD or COPY with symbolic link breaks image
**Actual behavior**
Image is broken when there is a symbolic link at the destination when ADD or COPY

**Expected behavior**
build should succeed and sources should be in destination

**To Reproduce**
1.  create Dockerfile
```dockerfile
FROM ubuntu
RUN mkdir -p /root/real && ln -sf /root/real /root/symlink
## cases
# case1: build success, but file path is wrong:  `/root/root/real/test-file`
COPY test-file /root/symlink/test-file 
# case2: image broken
COPY test-file /root/symlink/inner/test-file 
# case3: build fail
COPY test-dir/ /root/symlink 
# case4: image broken 
COPY test-dir/ /root/symlink/test-dir/ 
# case5: image broken
COPY test-dir/ /root/symlink/inner/test-dir/ 
```

2. image build with kaniko
```bash
$ mkdir test-dir && echo "test" > test-file && cp test-file test-dir/test-dir-file
$ /kaniko/executor --destination=shortstories/kaniko-test:case1 -v=trace
```

3. docker run
```bash
$ docker run --rm -it --entrypoint='/bin/bash' shortstories/kaniko-test:case4
Unable to find image 'shortstories/kaniko-test:case4' locally
test: Pulling from shortstories/kaniko-test
2746a4a261c9: Pull complete
4c1d20cdee96: Pull complete
0d3160e1d0de: Pull complete
c8e37668deea: Pull complete
ad9c552434bd: Pull complete
780db71f2ce6: Extracting [==================================================>]     257B/257B
docker: failed to register layer: Error processing tar file(exit status 1): mkdir /root/symlink: file exists.
See 'docker run --help'.
```

- test images
     - `shortstories/kaniko-test:case1`
     - `shortstories/kaniko-test:case2`
     - `shortstories/kaniko-test:case4`
     - `shortstories/kaniko-test:case5`

**Additional Information**
 - Dockerfile 
     - See `To Reproduce`
 - Build Context
     - See `To Reproduce`
 - Kaniko Image (fully qualified with digest)
     - `gcr.io/kaniko-project/executor:v0.15.0` (digest: `sha256:630f263d9123266b9f5420d9bc130e6a79306dbc312e5a7d35d922df391192bb`)

 **Triage Notes for the Maintainers**
 

 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [x] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by shortstories**
Fixes #942 

**Description**

Fixes an issue where the image is broken if there are symlink in the destination path when ADD or COPY

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

```
- Fixes an issue where symlinks resolved incorrectly
```

### CODE REVIEW

**Comment by shortstories** [comment]
@googlebot I signed it!

File: pkg/commands/copy.go [hunk 1]
```diff
@@ -197,21 +197,43 @@ func (cr *CachingCopyCommand) From() string {
 }
 
 func resolveIfSymlink(destPath string) (string, error) {
-	baseDir := filepath.Dir(destPath)
-	if info, err := os.Lstat(baseDir); err == nil {
+	if !filepath.IsAbs(destPath) {
```
Comment (cvgw) [inline pkg/commands/copy.go]: Why is this check needed?

File: pkg/commands/copy.go [hunk 2]
```diff
@@ -197,21 +197,43 @@ func (cr *CachingCopyCommand) From() string {
...
+		return "", errors.New("dest path must be abs")
+	}
+
+	pathPrefix := "/"
+	pathTokens := strings.Split(destPath, string(os.PathSeparator))
+	for i, pathToken := range pathTokens {
```
Comment (cvgw) [inline pkg/commands/copy.go]: Can you explain the idea behind this code. It's not clear what it accomplishes.

File: pkg/commands/copy.go [hunk 3]
```diff
@@ -59,11 +59,15 @@ func (c *CopyCommand) ExecuteCommand(config *v1.Config, buildArgs *dockerfile.Bu
 		if err != nil {
 			return err
 		}
+		if fi.IsDir() && !strings.HasSuffix(fullPath, string(os.PathSeparator)) {
```
Comment (cvgw) [inline pkg/commands/copy.go]: This should probably use `filepath.IsAbs(fullPath)`

File: pkg/commands/copy.go [hunk 4]
```diff
@@ -59,11 +59,15 @@ func (c *CopyCommand) ExecuteCommand(config *v1.Config, buildArgs *dockerfile.Bu
...
+			fullPath += "/"
```
Comment (cvgw) [inline pkg/commands/copy.go]: fullPath = filepath.Clean(fullPath)

File: pkg/commands/copy.go [hunk 5]
```diff
@@ -59,11 +59,15 @@ func (c *CopyCommand) ExecuteCommand(config *v1.Config, buildArgs *dockerfile.Bu
...
+		}
 		cwd := config.WorkingDir
 		if cwd == "" {
 			cwd = constants.RootDir
 		}
-		destPath, err := util.DestinationFilepath(src, dest, cwd)
+
+		destPath, err := util.DestinationFilepath(fullPath, dest, cwd)
```
Comment (cvgw) [inline pkg/commands/copy.go]: Why `fullPath` instead of `src`?

File: pkg/commands/copy.go (hunk 3 above)
Comment (shortstories) [reply pkg/commands/copy.go]: It is suffix, not prefix. I put this code in here to easily check if source is a directory.

File: pkg/commands/copy.go (hunk 4 above)
Comment (shortstories) [reply pkg/commands/copy.go]: `filepath.Clean()` removes trailing slash.

File: pkg/commands/copy.go (hunk 5 above)
Comment (shortstories) [reply pkg/commands/copy.go]: To check if source is a directory. Would it be right to call `IsDestDir(src)` once again inside `util.DestinationFilePath()`?

File: pkg/commands/copy.go (hunk 1 above)
Comment (shortstories) [reply pkg/commands/copy.go]: If it is rel path, it is not return value of `util.DestinationFilepath()`. Would it be correct to append the working directory to destPath in this function?

File: pkg/commands/copy.go (hunk 2 above)
Comment (shortstories) [reply pkg/commands/copy.go]: To resolve all symlinks in destination path.

The previous code failed to resolve unless symlink was a parent path. For example, when the destination is `/root/symlink/inner/target`, we expect it to be resolved to`/root/real/inner/target`, but previous code didn't work that way, it causing problems.
Similarly, if more than one symlink was found in the destination, it did not resolved correctly.
Problems also occur when symlink points to abs path.

So I split path into path elements and then re-joined them one by one. if symlinks is found in this process, it is replaced with a pointed path.
Then, if a path that does not exist, all remain path elements are need to be created, so they are just joined and returned.
This way, no matter how many symlinks are in the destination, no problem.

Comment (cvgw) [reply pkg/commands/copy.go]: Ah ok, thanks for that explanation. I think I better understand the problem now.

Would https://godoc.org/path/filepath#EvalSymlinks accomplish that goal?

File: pkg/commands/copy.go (hunk 3 above)
Comment (cvgw) [reply pkg/commands/copy.go]: woops, yup I see that mistake now. I guess I'm slightly confused about this check. So it is `true` for a fi that is a directory but whose `fullPath` does not end in a `/` ?

Is the goal of this check to make sure `fullPath` is formatted as expected?

File: pkg/commands/copy.go (hunk 4 above)
Comment (cvgw) [reply pkg/commands/copy.go]: :+1: my mistake

File: pkg/commands/copy.go (hunk 2 above)
Comment (shortstories) [reply pkg/commands/copy.go]: Yeah. At first I tried to solve this problem with `filepath.EvalSymlinks`. However, `file path.EvalSymlinks` could not be used because it returns a zero value string and error when` destPath` does not exist. We need to create a new directory even if `destPath` does not exist.

File: pkg/commands/copy.go (hunk 3 above)
Comment (shortstories) [reply pkg/commands/copy.go]: The goal of this code is what you say. I thought it would be inefficient to call `s.Lstat()` or` os.Stat()` every time when I pass src directly to a function.

File: pkg/commands/copy.go (hunk 2 above)
Comment (cvgw) [reply pkg/commands/copy.go]: Ah ok, that makes sense.

Would it be possible to use `EvalSymlink` by resolving the path from the longest to shortest segment?

Something like
```
for path != "/" {
  info, err := os.Lstat(path)
  if err != nil {
    if os.IsNotExist(err) {
      path = filepath.Dir(path)
      continue
    }
    // handle fatal err
  }
  path = path.EvalSymlinks(path)
}
```

WDYT?

Comment (shortstories) [reply pkg/commands/copy.go]: LGTM.

like this?
```go
	var nonexistentPaths []string

	newPath := destPath
	for newPath != "/" {
		_, err := os.Lstat(newPath)
		if err != nil {
			if os.IsNotExist(err) {
				dir, file := filepath.Split(newPath)
				newPath = filepath.Clean(dir)
				nonexistentPaths = append(nonexistentPaths, file)
				continue
			} else {
				return "", errors.Wrap(err, "failed to lstat")
			}
		}

		newPath, err = filepath.EvalSymlinks(newPath)
		if err != nil {
			return "", errors.Wrap(err, "failed to eval symlinks")
		}
		break
	}

	for i := len(nonexistentPaths)-1; i >= 0; i-- {
		newPath = filepath.Join(newPath, nonexistentPaths[i])
	}

	return filepath.Clean(newPath), nil

```

Comment (cvgw) [reply pkg/commands/copy.go]: Yup :)

Though a minor suggestion
```
for i := len(nonexistentPaths)-1; i >= 0; i-- {
  newPath = filepath.Join(newPath, nonexistentPaths[i])
}
```
to
```
sort.Reverse(nonexisitentPaths)
newPath = filepath.Join(newPath, nonexistentPaths...)
```

WDYT?

Comment (shortstories) [reply pkg/commands/copy.go]: In that case, the code actually looks like this:
```go
sort.Sort(sort.Reverse(sort.StringSlice(nonexistentPaths)))
newPath = filepath.Join(append([]string{newPath}, nonexistentPaths...)...)
```
Umm... I think it's a bit harder to read..
