### PR TITLE
828: clean up docker doc, fix context var in run cmd

### LINKED ISSUE #828: Run in Docker documentation lacks context
**Actual behavior**
The documentation for running Kaniko in a Docker container via `run_in_docker.sh` lacks appropriate context. The script does not appear to function correctly if a remote build context is specified, or if a Dockerfile is referenced outside the container filesystem:

```
~/go/src/github.com/GoogleContainerTools/kaniko/run_in_docker.sh /Users/mike/projects/kaniko/Dockerfile gs://gc-bucket/context.tar.gz gcr.io/project-id/nginx-alpine

docker: Error response from daemon: invalid mode: /workspace.
```

**Expected behavior**
As described in the documentation, this should be a valid command string:
```
./run_in_docker.sh <path to Dockerfile> <path to build context> <destination of final image>
```

**To Reproduce**
1. Run `run_in_docker.sh` using a local Dockerfile and remote build context.

**Additional Information**
 - Dockerfile 
```
FROM nginx:alpine
WORKDIR /root/
COPY www /usr/share/nginx/html
```
 - Build Context
```
COPY www /usr/share/nginx/html
```
 - Kaniko Image (fully qualified with digest)
```latest```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by codevbus**
Fixes #828. _in case of a bug fix, this should point to a bug and any other related issue(s)_

**Description**

- Updated documentation to reflect context compatibility of running Kaniko in Docker. 
- Added "" to variables in docker run command, added `${context}` var interpolation to run command.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [n/a] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
- Updated user-facing documentation for running in Docker.

```

### CODE REVIEW

**Comment by codevbus** [comment]
@priyawadhwa - Issue that came up while working on #812. Let me know if this needs any changes.

File: run_in_docker.sh [hunk 1]
```diff
@@ -35,9 +35,9 @@ if [[ ! -e $HOME/.config/gcloud/application_default_credentials.json ]]; then
...
 
 docker run \
-    -v $HOME/.config/gcloud:/root/.config/gcloud \
-    -v ${context}:/workspace \
+    -v "$HOME"/.config/gcloud:/root/.config/gcloud \
+    -v "$context":/workspace \
     gcr.io/kaniko-project/executor:latest \
-    --dockerfile ${dockerfile} --destination ${destination} --context dir:///workspace/ \
-    --cache=${cache}
+    --dockerfile "${dockerfile}" --destination "${destination}" --context "${context}" \
```
Comment (priyawadhwa) [inline run_in_docker.sh]: Since we mount $context to `/workspace` in the container itself, we want to  point kaniko to `/workspace`

File: README.md [hunk 2]
```diff
@@ -250,6 +255,17 @@ We can run the kaniko executor image locally in a Docker daemon to build and pus
   ./run_in_docker.sh <path to Dockerfile> <path to build context> <destination of final image>
   ```
 
+**NOTE**: When running in Docker, Kaniko expects the absolute path to a
```
Comment (priyawadhwa) [inline README.md]: This is correct, but instead of saying `kaniko expects ... a Dockerfile path inside the container` we could say `run_in_docker.sh expects a path to a Dockerfile relative to the absolute path of the build context`. Since this section is about run_in_docker.sh that makes more sense here.

**Comment by codevbus** [comment]
@priyawadhwa - made changes based on your feedback.

File: run_in_docker.sh [hunk 3]
```diff
@@ -35,9 +35,9 @@ if [[ ! -e $HOME/.config/gcloud/application_default_credentials.json ]]; then
 fi
 
 docker run \
-    -v $HOME/.config/gcloud:/root/.config/gcloud \
-    -v ${context}:/workspace \
+    -v "$HOME"/.config/gcloud:/root/.config/gcloud \
```
Comment (priyawadhwa) [inline run_in_docker.sh]: Are the changes to this file necessary?

Comment (codevbus) [reply run_in_docker.sh]: Most likely not, although it's generally safer to use "" in this case. Let me know if you want me to revert @priyawadhwa

Comment (priyawadhwa) [reply run_in_docker.sh]: That's alright, let's keep this! Thanks.

**Comment by priyawadhwa** [comment]
LGTM thanks for adding this!
