### PR TITLE
Resolving nested meta ARGs

### LINKED ISSUE #1117: Multistage Dockerfile combined ARG is not expanded
**Actual behavior**

If you combine multiple ARG at the top of the Dockerfile they are not expanded

**Expected behavior**

The ARG values provided are expanded, and can be passed to later stages. This is the behavior in Docker.

**To Reproduce**

Use the below Dockerfile as an example

**Additional Information**

```
ARG ALPINE_VERSION="3.6"
ARG ARG1="HELLO"
ARG ARG2="WORLD"
ARG COMBINED="${ARG1} ${ARG2}"

FROM alpine:${ALPINE_VERSION} AS builder

ARG COMBINED

RUN echo "$COMBINED"

COPY test.sh /tmp/test.sh

RUN chmod +x /tmp/test.sh \
 && ./tmp/test.sh

ENTRYPOINT [ "/bin/sh" ]
```

Here is Kaniko output

```
INFO[0000] Resolved base name alpine:${ALPINE_VERSION} to alpine: 
INFO[0000] Resolved base name alpine:${ALPINE_VERSION} to alpine: 
INFO[0000] Retrieving image manifest alpine:3.6         
INFO[0004] Retrieving image manifest alpine:3.6         
INFO[0006] Built cross stage deps: map[]                
INFO[0006] Retrieving image manifest alpine:3.6         
INFO[0008] Retrieving image manifest alpine:3.6         
INFO[0010] Unpacking rootfs as cmd RUN echo "$COMBINED" requires it. 
INFO[0011] Taking snapshot of full filesystem...        
INFO[0011] Resolving paths                              
INFO[0011] ARG COMBINED                                 
INFO[0011] RUN echo "Arg = $COMBINED"                   
INFO[0011] cmd: /bin/sh                                 
INFO[0011] args: [-c echo "$COMBINED"]            
${ARG1} ${ARG2}
INFO[0011] Taking snapshot of full filesystem...        
INFO[0011] Resolving paths                              
INFO[0011] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0011] COPY test.sh /tmp/test.sh                    
INFO[0011] Resolving paths                              
INFO[0011] Taking snapshot of files...                  
INFO[0011] RUN chmod +x /tmp/test.sh  && ./tmp/test.sh  
INFO[0011] cmd: /bin/sh                                 
INFO[0011] args: [-c chmod +x /tmp/test.sh  && ./tmp/test.sh] 
${ARG1} ${ARG2}
INFO[0011] Taking snapshot of full filesystem...        
INFO[0011] Resolving paths                              
INFO[0011] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0011] ENTRYPOINT [ "/bin/sh" ] 
```

Here is example Docker output

```
docker image build --tag test:latest .

Sending build context to Docker daemon  3.072kB
Step 1/10 : ARG ALPINE_VERSION="3.6"
Step 2/10 : ARG ARG1="HELLO"
Step 3/10 : ARG ARG2="WORLD"
Step 4/10 : ARG COMBINED="${ARG1} ${ARG2}"
Step 5/10 : FROM alpine:${ALPINE_VERSION} AS builder
 ---> 43773d1dba76
Step 6/10 : ARG COMBINED
 ---> Running in 297804dc64c1
Removing intermediate container 297804dc64c1
 ---> c8a3dd39a0e6
Step 7/10 : RUN echo "$COMBINED"
 ---> Running in 259afbb5aadf
HELLO WORLD
Removing intermediate container 259afbb5aadf
 ---> b84c256a6de3
Step 8/10 : COPY test.sh /tmp/test.sh
 ---> b9c406402c2b
Step 9/10 : RUN chmod +x /tmp/test.sh  && ./tmp/test.sh
 ---> Running in 79d090345d3e
HELLO WORLD
Removing intermediate container 79d090345d3e
 ---> d968fbee09c3
Step 10/10 : ENTRYPOINT [ "/bin/sh" ]
 ---> Running in 4b51729d5e7f
Removing intermediate container 4b51729d5e7f
 ---> 8dd90feb609a
Successfully built 223ac995255d
Successfully tagged test:latest
```

The test.sh

```
#!/bin/sh

echo "$COMBINED"
exit 0
```

I have tested with the following versions with the same result:
- v0.18.0
- v0.17.1
- edge (sha256:d229ff9b49c9c9ea4edab835f3773af09c015152d8ddfeb0ac356787e70df09c)

 
 **Triage Notes for the Maintainers**
 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [X] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [X] </li></ul>|

### PR DESCRIPTION
**Pull request by ljakimczuk**
Fixes #1117

**Description**

Adding an extra step that expands all meta ARGs against themselves and build ARGs in the [ParseStages](https://github.com/GoogleContainerTools/kaniko/blob/cb11a9982cbf2bd207ced5b64fc524a60a6e14ac/pkg/dockerfile/dockerfile.go#L38). This expands the nested ARGs.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [ ] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Resolving nested meta ARGs.

### CODE REVIEW

File: pkg/dockerfile/dockerfile_test.go [hunk 1]
```diff
@@ -65,11 +68,11 @@ func Test_ParseStages_ArgValueWithQuotes(t *testing.T) {
 		t.Fatal("length of stages expected to be greater than zero, but was zero")
 	}
 
-	if len(metaArgs) != 2 {
+	if len(metaArgs) != 5 {
 		t.Fatalf("length of stage meta args expected to be 2, but was %d", len(metaArgs))
```
Comment (tejal29) [inline pkg/dockerfile/dockerfile_test.go:72]:
```suggestion
		t.Fatalf("length of stage meta args expected to be 5, but was %d", len(metaArgs))
```
