### PR TITLE
fix flake TestRun/Dockerfile_test_copy_symlink

### LINKED ISSUE #1019: [Flake]  integration test flake Dockerfile_test_copy_symlink
the `Dockerfile_test_copy_symlink` has failed multiple times on Jenkins. 
This test passes on Travis every single time. 
Re-triggering the failed build fixes it. 

```
--- FAIL: TestRun/test_Dockerfile_test_copy_symlink (16.90s)
        integration_test.go:188: diff = [
              {
                "Image1": "gcr.io/kaniko-test/docker-dockerfile_test_copy_symlink",
                "Image2": "gcr.io/kaniko-test/kaniko-dockerfile_test_copy_symlink",
                "DiffType": "File",
                "Diff": {
                  "Adds": [
                    {
                      "Name": "/tmp/link",
                      "Size": -1
                    }
                  ],
                  "Dels": null,
                  "Mods": [
                    {
                      "Name": "/tmp",
                      "Size1": 6,
                      "Size2": 11
                    }
                  ]
                }
              },
              {
                "Image1": "gcr.io/kaniko-test/docker-dockerfile_test_copy_symlink",
                "Image2": "gcr.io/kaniko-test/kaniko-dockerfile_test_copy_symlink",
                "DiffType": "Metadata",
                "Diff": {
                  "Adds": [],
                  "Dels": []
                }
              }
            ]
        integration_test.go:191: []integration.diffOutput differ (-got, +want):   []integration.diffOutput{
              	{
              		Image1:   "gcr.io/kaniko-test/docker-dockerfile_test_copy_symlink",
              		Image2:   "gcr.io/kaniko-test/kaniko-dockerfile_test_copy_symlink",
              		DiffType: "File",
              		Diff: &integration.fileDiffResult{
            - 			Adds: []integration.fileDiff{{Name: "/tmp/link", Size: -1}},
            + 			Adds: nil,
              			Dels: nil,
              		},
              	},
              	{Image1: "gcr.io/kaniko-test/docker-dockerfile_test_copy_symlink", Image2: "gcr.io/kaniko-test/kaniko-dockerfile_test_copy_symlink", DiffType: "Metadata", Diff: &integration.metaDiffResult{Adds: []string{}, Dels: []string{}}},
              }

```

### PR DESCRIPTION
**Pull request by tejal29**
Fixes #1019

In this PR
1. Replicate `docker build` behavior by copying the target file to destination link.
2. Create file with same uid and gid as target.
3. Added different scenarios for `ln` in integration test.

1. Manually verified by building use kaniko and docker. 
2. Verified by running the test 10 times
````
 go test ./integration/...  -run TestRun/test_Dockerfile_test_copy_symlink -count 10 -v --bucket tejal-test --repo gcr.io/tejal-test

...
=== CONT  TestRun/test_Dockerfile_test_copy_symlink
--- PASS: TestRun (0.00s)
    --- PASS: TestRun/test_Dockerfile_test_copy_symlink (0.91s)
        integration_test.go:188: diff = [
              {
                "Image1": "gcr.io/tejal-test/docker-dockerfile_test_copy_symlink",
                "Image2": "gcr.io/tejal-test/kaniko-dockerfile_test_copy_symlink",
                "DiffType": "File",
                "Diff": {
                  "Adds": null,
                  "Dels": null,
                  "Mods": null
                }
              },
              {
                "Image1": "gcr.io/tejal-test/docker-dockerfile_test_copy_symlink",
                "Image2": "gcr.io/tejal-test/kaniko-dockerfile_test_copy_symlink",
                "DiffType": "Metadata",
                "Diff": {
                  "Adds": [],
                  "Dels": []
                }
              }
            ]
PASS
ok  	github.com/GoogleContainerTools/kaniko/integration	140.239s


```

### CODE REVIEW

File: pkg/util/fs_util.go [hunk 1]
```diff
@@ -616,7 +616,7 @@ func CopySymlink(src, dest, buildcontext string) (bool, error) {
 	if err := createParentDirectory(dest); err != nil {
 		return false, err
 	}
-	return false, os.Symlink(link, dest)
+	return CopyFile(link, dest, buildcontext, uid, gid)
```
Comment (cvgw) [inline pkg/util/fs_util.go]: Why the change from link to copy? I'm struggling to connect this change to a flaky test.

File: pkg/util/fs_util.go [hunk 2]
```diff
@@ -789,11 +789,15 @@ func getSymlink(path string) error {
 func CopyFileOrSymlink(src string, destDir string) error {
 	destFile := filepath.Join(destDir, src)
 	if fi, _ := os.Lstat(src); IsSymlink(fi) {
-		link, err := os.Readlink(src)
+		link, err := EvalSymLink(src)
 		if err != nil {
 			return err
 		}
-		return os.Symlink(link, destFile)
+		linkPath := filepath.Join(destDir, link)
```
Comment (cvgw) [inline pkg/util/fs_util.go]: Could you explain this code a bit? I'm having trouble wraping my head around it.

It looks like `linkPath` is the resolved path of `src` joined with `destDir`. I'm confused how we can be sure this path exists.

File: pkg/util/fs_util.go (hunk 1 above)
Comment (tejal29) [reply pkg/util/fs_util.go]: This test was flaky because of 2 reasons
1. The `link` value was `/tmp/target`. 
   We were linking `kaniko/0/tmp/link` to `/tmp/target` -  should have been `/kaniko/0/tmp/link`
2. The target file `/tmp/target` was getting wiped out before call to `os.Symlink(link, dest)` . - this caused flakiness. 

In the description, i mentioned i fixed the `CopySymlink` to replicate docker behavior. Docker copies the target file to destination link and hence i replaced `os.Symlink` to `CopyFile`.

File: pkg/util/fs_util.go (hunk 2 above)
Comment (tejal29) [reply pkg/util/fs_util.go]: This was error 1 mentioned in [here](https://github.com/GoogleContainerTools/kaniko/pull/1030#discussion_r376664809)

This ensures, we are copying/creating the required file in kaniko sratch workspace.
