### PR TITLE
Bugfix: Reproducible layers with whiteout

### LINKED ISSUE #900: --reproducible leads to different layers in resulting image
**Actual behavior**
Building an image twice using the `--reproducible` flag leads to different layers in the final images.

**Expected behavior**
Image layers should have the same hash as the content is the same and the reproducible flag was used.

**To Reproduce**
```shell
mkdir ctx && cd ctx
echo "Foo" >foo
echo "Fooo" >fooo
echo "Bar" >bar

cat >Dockerfile <<'EOF'
FROM gcr.io/distroless/java
USER nonroot
COPY foo* /
COPY bar /
EOF

docker run -it -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e no_proxy=$no_proxy --rm -v $(pwd):/data  \
         -v ~/.docker/config.json:/kaniko/.docker/config.json \
         gcr.io/kaniko-project/executor:v0.14.0 \
              --reproducible \
              --context /data \
              --dockerfile Dockerfile \
              --destination myrepo.com/img:foo

docker run -it -e http_proxy=$http_proxy -e https_proxy=$https_proxy -e no_proxy=$no_proxy --rm -v $(pwd):/data  \
         -v ~/.docker/config.json:/kaniko/.docker/config.json \
         gcr.io/kaniko-project/executor:v0.14.0 \
              --reproducible \
              --context /data \
              --dockerfile Dockerfile \
              --destination myrepo.com/img:bar 
```

Layers in myrepo.com/img:foo and myrepo.com/img:bar have different hashes.

**Additional Information**
see steps to reproduce

also described this in in #710 - this issue is however not releated to caching

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by hlubek**
Fixes #900 (which was not fully solved).

**Description**

When deleting files of previous layers, the whiteout files
were not added to the tar file in a consistent order.

This change adds a stable sorting to the whiteout files and
adds unit tests to check for stable sorting.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [x] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

No user facing changes.

### CODE REVIEW

File: pkg/snapshot/snapshot_test.go [hunk 1]
```diff
@@ -391,6 +391,160 @@ func TestSnasphotPreservesFileOrder(t *testing.T) {
...
+	newFileNames := []string{}
+
+	for fileName := range newFiles {
+		newFileNames = append(newFileNames, fileName)
+	}
+
+	filesInTars := [][]string{}
+
+	for i := 0; i <= 2; i++ {
+		testDir, snapshotter, cleanup, err := setUpTest()
```
Comment (hlubek) [inline pkg/snapshot/snapshot_test.go:415]: The code is not ideal (using defer in a loop) and the non-determinism is a little hard to understand (converting from a map to a slice). But I chose to impolement the new tests like `TestSnasphotPreservesFileOrder` for consistency.

**Comment by hlubek** [comment]
@googlebot I signed it!
