### PR TITLE
Resolve relative paths to absolute paths in command line arguments

### LINKED ISSUE #732: Relative paths don't work with `--context`, `--tarPath`, and others...
# Actual behavior
Upon executing, the `executor` binary changes its root directory to `/` as seen here https://github.com/GoogleContainerTools/kaniko/blob/master/cmd/executor/cmd/root.go#L84

This prevents the use of relative directories in the `executor` command line arguments.

For example:
- Imagine a directory `/tmp/build` 
- with a subdirectory `myworkspace/` containing the `Dockerfile` (i.e. `/tmp/build/myworkspace/Dockerfile`)
- Running the following will fail:
```
cd /tmp/build
/kaniko/executor --dockerfile=Dockerfile --context=myworkspace/ --destination=image --tarPath=image.tar --cache=true --cache-dir=./cache/ --no-push
```
- With the error:
```
Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile
```

# Expected behavior
Kaniko should allow the use of **relative paths** in its command line and honor them.

# Additional Information
The current behavior is also confusing because the `--dockerfile` argument **does** allow a relative path. 

That is, the following command line works: 
```
cd /tmp/build
/kaniko/executor --dockerfile=myworkspace/Dockerfile --destination=image --tarPath=image.tar --cache=true --cache-dir=./cache/ --no-push
```

But fails as soon as the Dockerfile tries to use a "workspace" file
```
error building image: error building stage: lstat /myworkspace/entrypoint.sh: no such file or directory
```

# Related issues
https://github.com/GoogleContainerTools/kaniko/issues/731
https://github.com/GoogleContainerTools/kaniko/issues/675

### PR DESCRIPTION
**Pull request by huguesalary**
The executor accepts a few arguments `--dockerfile`, `--context`, `--cache-dir` and
`--digest-file` that all represent paths. This commits allows those paths to
be relative to the working directory of the executor.

This code assumes `context` is an actual path and not a URL, which it should be when the new `resolveRelativePaths()` function introduced by this commit is called.

Fixes #732 #731 #675

### CODE REVIEW

File: cmd/executor/cmd/root.go [hunk 1]
```diff
@@ -227,6 +230,37 @@ func resolveSourceContext() error {
...
+		if filepath.IsAbs(*p) {
+			logrus.Debugf("Path %s is absolute, skipping", *p)
+			continue
+		}
+
+		// Resolve relative path to absolute path
+		var err error
+		absp := *p
+		if *p, err = filepath.Abs(*p); err != nil {
+			return errors.Wrapf(err, "Couldn't resolve relative path %s to an absolute path", p)
```
Comment (huguesalary) [inline cmd/executor/cmd/root.go]: On this line, `p` should be `*p` I'll push a fix asap.

**Comment by huguesalary** [comment]
Sure thing, though I am unclear as to where exactly I should add my test files. Would you mind pointing this out to me?

**Comment by huguesalary** [comment]
Also, I force pushed again because `logrus.Debugf("Resolved relative path %s to %s", *p, absp)` was outputting `Resolved relative path [absolute_path] to [old_relative_path]` (instead of `Resolved relative path [old_relative_path] to [absolute_path]`)

**Comment by priyawadhwa** [comment]
For sure -- we have an [integration](https://github.com/GoogleContainerTools/kaniko/tree/master/integration) test folder with all of our integration tests. for example, this is the test for [caching](https://github.com/GoogleContainerTools/kaniko/blob/master/integration/integration_test.go#L352).

You could add another test here to build a kaniko image with relative paths passed in, using the [context](https://github.com/GoogleContainerTools/kaniko/tree/master/integration/context) directory for the context and using a Dockerfile in the [dockerfiles](https://github.com/GoogleContainerTools/kaniko/tree/master/integration/dockerfiles) directory to build. If the build completes succesfully, we can say the test has passed. Let me know if you have any more questions!

**Comment by huguesalary** [comment]
@priyawadhwa Thanks! Should I create a new Dockerfile or should I follow the caching test model and write a test that builds every Dockerfile available in the test directory?

**Comment by priyawadhwa** [comment]
Creating a new Dockerfile or using one of the existing ones and testing once should be sufficient.

File: cmd/executor/cmd/root.go [hunk 2]
```diff
@@ -227,6 +230,37 @@ func resolveSourceContext() error {
 	return nil
 }
 
+func resolveRelativePaths() error {
```
Comment (tejal29) [inline cmd/executor/cmd/root.go]: @huguesalary Thank you for your contributions. This looks really good. However can we please some unit test for this?

Can you refactor `resolveRelativePaths()` to accept opts? That ways we can easily write unit tests


```suggestion
func resolveRelativePaths(opts config.KanikoOptions{}) error {
```

Now, you can creates tests where

```
func TestResolveRelativePaths(t *testing.T) {
	tests := []struct {
		description  string
		opts config.KanikoOptions
               expected config.KanikoOptions
               shdErr  bool 
	}{
            {
                description: "dockerfile path  is absolute",
                opts: config.KanikoOptions{
                           DockerfilePath: "/abs/dockerfile",
                        },
               expected: config.KanikoOptions{
                           DockerfilePath: "/abs/dockerfile",
                        },
            }

	}
	for _, tt := range tests {
           actual := resolveRelativePaths(tt.opts)
           t.CheckDeepEqualAndError(tt.shdErr, actual, tt.expected, tt.opts)
	}
}


```

**Comment by huguesalary** [comment]
Hi @tejal29 sure thing I'll add your suggestion and some unit tests

**Comment by trungdq88** [comment]
Hi, thank you for your contribution to this great repo. Just to put a note that I suspect this PR broke my build this morning:

I used `--context=dir://workspace` in my `cloudbuild.yaml`.

Build logs before:
```
Step #1: WORKDIR /code                                
Step #1: cmd: workdir                                 
Step #1: Changed working directory to /code           
Step #1: No files changed in this command, skipping snapshotting. 
Step #1: Using files from context: [workspace/build-pool/main] 
Step #1: COPY build-pool/main /code                   
Step #1: Taking snapshot of files...                  
Step #1: ENTRYPOINT ./something.sh 
Step #1: No files changed in this command, skipping snapshotting. 
Finished Step #1
```

Build logs after:
```
Step #1: WORKDIR /code                                
Step #1: cmd: workdir                                 
Step #1: Changed working directory to /code           
Step #1: No files changed in this command, skipping snapshotting. 
Step #1: error building image: error building stage: lstat /workspace/workspace/build-pool/main: no such file or directory
```

My config was incorrect. After I change the config to `--context=/workspace` it worked fine.

I would be appreciate if we could make releases backward compatible, even if the old behavior is incorrect because maybe there are people depend on it. Or at least put a note in the changelog.

If this PR did not cause the broken build as I suspected: I am sorry, please ignore this.

Thanks!
