### PR TITLE
Expand build argument from environment when no value specified

### LINKED ISSUE #713: Kaniko's --build-arg accepts only literal values
Actual behavior
Using encrypted variables is working fine with cloud build image. 
Docker also supports copying a value from the environment by just specifying NAME[1].
But if I switch to kaniko, it doesn't pass the secret values as a build argument. Kaniko works only when I pass constant value, eg NAME=value. 

Expected behavior
Be able to use the same way as docker does, the environment variables on Kaniko

To Reproduce

command:
gcloud builds submit --config=cloudbuild-kaniko.yaml .

Dockerfile:
FROM busybox
ARG THE_SECRET
RUN echo "::${THE_SECRET}::"

cloudbuild-kaniko.yaml:
steps:
- id: bash
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: "bash"
  args: ['-c', 'echo "$$THE_SECRET"']
  secretEnv: ['THE_SECRET']
- id: docker
  name: 'gcr.io/kaniko-project/executor:latest'
  args: 
    - --destination=gcr.io/[project-id]/image
    - --build-arg=THE_SECRET=$$THE_SECRET 
    - --build-arg=THE_SECRET=secrettttttt  
  secretEnv: ['THE_SECRET']
secrets:
- kmsKeyName: projects/[project-id]/locations/global/keyRings/tinkering/cryptoKeys/cloud-build-demo
  secretEnv:
    THE_SECRET: XXXXXX

____
[1]: https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables---build-arg

### PR DESCRIPTION
**Pull request by antechrestos**
Fixes #713 

**Description**

This change adds the feature of getting value of build argument from environment when build argument is specified as follows

`/kaniko/executor .... --build-arg MY_ARGUMENT ...` 

**Submitter Checklist**

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [x] Adds integration tests if needed.

**Reviewer Notes**

- [x] The code flow looks good. 
- [x] Unit tests and or integration tests added.

**Release Notes**

```
Allow user to provide build argument from environment variable as follows:
$> export MY_ARGUMENT="the value"
$> /kaniko/executor ... --build-arg MY_ARGUMENT ...
Or
$> docker run -e MY_ARGUMENT="the value" gcr.io/kaniko-project/executor ... --build-arg MY_ARGUMENT ...
```

### CODE REVIEW

**Comment by antechrestos** [comment]
@cvgw As promised... Do I need to add integration test?

**Comment by tejal29** [comment]
Thank you so much for your contribution!

**Comment by stewi2** [comment]
> won't `docker -e SOME_SECRET=secret-value run ....` output the value of the secret to the log/shell history?

At least that part can be solved via a .env file. I.e.

```
docker --env-file .secrets run ....
```

with `.secrets` containing this:

```
SOME_SECRET=secret-value
```

Granted, that file would need to be written to disk first, but this is a common way to pass along environment variables without exposing them via the command line.

**Comment by antechrestos** [comment]
@tejal29 you're welcome
@cvgw I added it. To do so I added a new dedicated dockerfile. I also added a way to pass environment variable to build (with `cmd.Env` for docker build and `-e` for kaniko build as kaniko build is done inside docker) and also tested the expansion of docker variable.
For this test a check of output is provided te do a research on argument value and ensure that it is not printed.

File: cmd/executor/cmd/root.go [hunk 1]
```diff
@@ -206,6 +207,17 @@ func resolveDockerfilePath() error {
 	return errors.New("please provide a valid path to a Dockerfile within the build context with --dockerfile")
 }
 
+// resolveEnvironmentBuildArgs replace build args without value by the same named environment variable
+func resolveEnvironmentBuildArgs(arguments []string, resolver func(string) string) {
```
Comment (cvgw) [inline cmd/executor/cmd/root.go]: So this will take an argument like `FOO` and replae it with `FOO=FOO` ?

File: integration/images.go [hunk 2]
```diff
@@ -71,6 +78,36 @@ var additionalKanikoFlagsMap = map[string][]string{
...
 }
 
+// output check to do when building with kaniko
+var outputChecks = map[string]func(string, []byte) error{
+	"Dockerfile_test_arg_secret": checkArgsNotPrinted,
+}
+
+// Checks if argument are not printed in output.
+// Argument may be passed through --build-arg key=value manner or --build-arg key with key in environment
+func checkArgsNotPrinted(dockerfile string, out []byte) error {
```
Comment (cvgw) [inline integration/images.go]: So this checks to make sure the value of none of the build args are logged? It makes no distinction between whether they were added as literals or expanded from the env?

Comment (antechrestos) [reply integration/images.go]: @cvgw I could have make the distinction in the test, however I could not find any way to make the distinction in the code as env like variable (env, arg and meta arg ) are used everywhere as a mere string `key=value` and could not make the distinction without breaking everything.
Do you want I change the test? Or everything?

File: cmd/executor/cmd/root.go (hunk 1 above)
Comment (antechrestos) [reply cmd/executor/cmd/root.go]: @cvgw this will take the argument array such as `[ "foo=bar", "EnvVariable" ]` crawl through it and replace any argument without `=` with `"EnvVariable=EnvValue"` **if** a  value was returned by `resolver` function  (`os.Getenv` in prod code, mocked function in tests). If zero length value returned, it will be replaced with `"EnvVariable="`

File: integration/images.go (hunk 2 above)
Comment (cvgw) [reply integration/images.go]: No changes needed. Was just clarifying for my owner understanding. I think it's reasonable to not log any ARG values.

File: cmd/executor/cmd/root.go (hunk 1 above)
Comment (cvgw) [reply cmd/executor/cmd/root.go]: Thanks for explaining, cheers

**Comment by antechrestos** [comment]
@cvgw something went wrong with kaniko. However, things went well in Travis 🤔...

**Comment by tejal29** [comment]
@antechrestos i triggered a rebuilt. Previous failure was a flake.

**Comment by antechrestos** [comment]
@tejal29 thanks

**Comment by antechrestos** [comment]
@tejal29 😢

**Comment by antechrestos** [comment]
@tejal29  I have rebased my branch. I am not sure it might change anything :thinking:

**Comment by antechrestos** [comment]
@cvgw @tejal29 may I have another try with kokoro? :pray:

**Comment by tejal29** [comment]
@antechrestos The travis test passed, so i am going to merge this in!

**Comment by antechrestos** [comment]
@tejal29 at our own risk 😊

**Comment by sourcec0de** [comment]
THANK YOU! ❤️

**Comment by nhed** [comment]
Thanks this is so helpful (albeit undocumented) feature
