### PR TITLE
fix(WORKDIR): use the config.User for the new dir permissions

### LINKED ISSUE #2259: WORKDIR does no create the directory with the ownership of the active USER
**Actual behavior**
When WORKDIR creates the missing directory, it leaves it with the `root:root` ownership - does no change the ownership to the user switched with the latest USER command.

**Expected behavior**
When Docker builds the image, it creates the missing WORKDIR with the ownership of the active USER.
Steps:
1. Have a Dockerfile with the provided content below
2. Run `docker run --rm -it $(docker build -q --no-cache .) ls -al /`
```
...
drwxr-xr-x    2 9999     9999          4096 Sep 20 20:01 work
...
```

**To Reproduce**
1. Have a Dockerfile with the provided content below
2. Build the image with Kaniko (ie. `./run_in_docker.sh Dockerfile /path/to/context/ gcr.io/project/image-name
3. Check the directory created by WORKDIR: `docker run --rm -it gcr.io/project/image-name ls -al /`
```
...
drwxr-xr-x    2 root     root          4096 Sep 20 20:13 work
...
```

**Additional Information**
 - Dockerfile 
```Dockerfile
FROM busybox

USER 9999
WORKDIR /work
```
 - Build Context
No files needed.
 - Kaniko Image (fully qualified with digest)
`gcr.io/kaniko-project/executor` `sha256:1f982af0b54be748221d9a35dcfa608660ab3d51229aa56bde5416f75aff7561`

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [X] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by arisro**
Fixes #2259, probably #477, probably #1340 (does not repro anymore)

**Description**
WORKDIR ignores the currently set USER and creates the new directories with the root user ownership.

This changes that, by executing a chown after the mkdir if needed, and also handle the case where the provided USER is an uid and the passwd file is not available to resolve to the username.

The PR contains a smoke integration test as the container-diff cannot yet check file ownership (https://github.com/GoogleContainerTools/container-diff/issues/308) - it just makes sure the build does not error out for various cases and that the diff looks good.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [X] Adds integration tests if needed.

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**
```
- kaniko creates the new directories from WORKDIR with the correct ownership
```

### CODE REVIEW

File: pkg/util/command_util.go [hunk 1]
```diff
@@ -442,8 +442,8 @@ func LookupUser(userStr string) (*user.User, error) {
 	userObj, err := user.Lookup(userStr)
 	if err != nil {
 		unknownUserErr := new(user.UnknownUserError)
-		// only return if it's not an unknown user error
-		if !errors.As(err, unknownUserErr) {
+		// only return if it's not an unknown user error or the passwd does not exist
+		if !errors.As(err, unknownUserErr) && !strings.Contains(err.Error(), "no such file") {
```
Comment (imjasonh) [inline pkg/util/command_util.go:446]: Instead of matching the error text string, it looks like you can check [`os.IsNotExist(err)`](https://pkg.go.dev/os#IsNotExist)

Comment (arisro) [reply pkg/util/command_util.go]: Thanks @imjasonh. Works like a charm. Updated the PR.

**Review by imjasonh — APPROVED** [review]
