### PR TITLE
fix: ensure images layers correspond with the image media type

### LINKED ISSUE #2713: Prepopulating cache with kaniko warmer still causes problems with manifest mediaType
**Actual behavior**
Thank you big time for fixing #1836.   
We use kaniko in a gitlab CI job and I noticed that when building a Docker image (at least the one below) with pre populating the cache with kaniko's `warmer` the push to the gitlab registry will fail. But once the `warmer` is not used any more the push to gitlab's registry works.

Error with the warmer:
```bash
error pushing image: failed to push to destination gitlab....com:4567/user/repo/warmertest:latest: PUT https://gitlab.....com:4567/v2/user/repo/warmertest/manifests/new2: MANIFEST_INVALID: manifest invalid; mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'
```

**Expected behavior**
Using kaniko `warmer` should not change the build result (when only warming with the base image).

**To Reproduce**
Everything of the following in done inside Docker
```bash
docker run -it --rm --entrypoint=/busybox/sh gcr.io/kaniko-project/executor:v1.15.0-debug
```

Failing behaviour:
```bash
# add login credential for gitlab registry beforehand
mkdir /kcache
/kaniko/warmer --cache-dir=/kcache --image=condaforge/mambaforge:23.3.1-0
/kaniko/executor --context /workspace --dockerfile /workspace/Dockerfile --cache=true --cache-copy-layers=false --cache-dir=/kcache --destination gitlab.....com:4567/user/repo/warmertest:latest --verbosity=info --cleanup
``` 

Working behaviour:
```bash
# add login credential for gitlab registry beforehand
mkdir /kcache
# do not warm with base image
/kaniko/executor --context /workspace --dockerfile /workspace/Dockerfile --cache=true --cache-copy-layers=false --cache-dir=/kcache --destination gitlab.....com:4567/user/repo/warmertest:latest --verbosity=info --cleanup
``` 
**Note: Corporate URL and username are removed**

**Additional Information**
 - Dockerfile 
    ```Dockerfile
    FROM condaforge/mambaforge:23.3.1-0
    RUN mamba update --all -q -y
    ```
 - Kaniko Image (fully qualified with digest)
    gcr.io/kaniko-project/executor@sha256:9a798741047d3761221100f586ea9fa8a3f09957176630faeb77923894b7355a
    gcr.io/kaniko-project/executor:v1.15.0-debug
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [x] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by loganprice**
Fixes #2713 _in case of a bug fix, this should point to a bug and any other related issue(s)_

**Description**

- Ensure zstd compression only gets applied to oci images. 
- When adding a layer to an image ensure that they are compatible if not convert them. 
- Create function to convert mediatypes between oci and docker types.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [x] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

### CODE REVIEW

File: pkg/executor/build.go [hunk 1]
```diff
@@ -501,6 +501,29 @@ func (s *stageBuilder) saveSnapshotToLayer(tarPath string) (v1.Layer, error) {
 		return nil, nil
 	}
 
+	layerOpts := s.getLayerOptionFromOpts()
+	imageMediaTtpe, err := s.image.MediaType()
```
Comment (aaron-prindle) [inline pkg/executor/build.go:505]: nit(typo): s/imageMediaTtype/imageMediaType

**Comment by aaron-prindle** [comment]
Thanks for the PR here @loganprice.  Just tested this, works great!  Left one small nit comment related to a typo.

File: pkg/executor/build.go (hunk 1 above)
Comment (loganprice) [reply pkg/executor/build.go]: fixed typo

**Review by aaron-prindle — APPROVED** [review]
