### PR TITLE
Don't write whiteout files to directories that were replaced with files or links

### LINKED ISSUE #2308: when replacing a folder by symlink : i get corrupt images when pulling : failed to mknod("somefile", S_IFCHR, 0): no such file or directory
**Actual behavior**

When replacing a folder by symlink i get corrupt images , docker pull will fail with  :
Failed to register layer: Error processing tar file(exit status 1): failed to mknod("/etc/fail2ban/action.d", S_IFCHR, 0): no such file or directory

**Expected behavior**
Be able to pull the image

**To Reproduce**

The error doesn't seems t happen with every files/folder.
I tried disabling all caches to be sure

The build/pull works when using the dockerfile directly with docker build command
The build works with kaniko but appears corrupt as i can t pull it

**Additional Information**
 - Dockerfile 

FROM  quay.io/centos/centos:stream9
RUN dnf -y update && dnf -y install systemd
RUN /usr/bin/systemctl mask systemd-logind && /usr/bin/systemctl mask systemd-hostnamed && /usr/bin/systemctl mask dbus-
RUN  ln -s /data/git_conf/conf/systemd/journald.conf.d /etc/systemd/journald.conf.d
RUN dnf install -y rsyslog && mv -f /etc/rsyslog.d /etc/rsyslog.d.orig && ln -s /data/git_conf/conf/rsyslog/rsyslog.d /etc/rsyslog.d
RUN systemctl enable rsyslog
RUN dnf -y install procps net-tools
STOPSIGNAL SIGRTMIN+3
CMD [ "/sbin/init" ]

This one build and pull fine even with the the broken symlink that will lead to a mounted volume set in docker compose

FROM previousdockerimage
RUN dnf -y update  && dnf install -y epel-release && dnf -y install fail2ban && systemctl enable fail2ban && dnf clean all
RUN rm -rf  /etc/fail2ban && ln -s  /data/git_conf/conf/fail2ban  /etc/fail2ban
STOPSIGNAL SIGRTMIN+3
EXPOSE 22
CMD [ "/sbin/init" ]

When pulling this one errors with
Error processing tar file(exit status 1): failed to mknod("/etc/fail2ban/action.d", S_IFCHR, 0): no such file or directory
The folder action.d isn't supposed to be there anymore.

 - Build Context

Nothing special, here is the gitlab ci/cd, but i get the same error running it manually

make_fail2ban:
  stage: make_fail2ban
  image:
    name: gcr.io/kaniko-project/executor:v1.9.1-debug
    entrypoint: [""]
  script:
    - /kaniko/executor  -c /workspace --dockerfile https://mygitlab/mydockerfile --destination "${CI_REGISTRY_IMAGE}/fail2ban:${CI_COMMIT_TAG}" 

 - Kaniko Image (fully qualified with digest)
 
gcr.io/kaniko-project/executor:v1.9.1-debug
sha256:ac169723b2076f9d5804f4bc05c98397e286da6fdcdd5a09fdc179f06ccb3be1

 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by andreasf**
Fixes #2308

**Description**

If a non-empty directory gets replaced with something other than a directory (e.g. file or symlink), the files in that directory also get deleted. However, there should not be any whiteout files for them in the layer. If there were, the resulting tar file would not be extractable.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [x] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

### CODE REVIEW

File: pkg/snapshot/snapshot.go [hunk 1]
```diff
@@ -247,6 +255,21 @@ func writeToTar(t util.Tar, files, whiteouts []string) error {
...
+// Returns true if a parent of the given path has been replaced with anything other than a directory
+func parentPathIncludesNonDirectory(path string) (bool, error) {
+	for _, parentPath := range util.ParentDirectories(path) {
+		lstat, err := os.Lstat(parentPath)
+		if err != nil {
+			return false, err
+		}
+
+		if !lstat.IsDir() {
+			return true, err
```
Comment (gabyx) [inline pkg/snapshot/snapshot.go:267]: return nil here

File: pkg/snapshot/snapshot_test.go [hunk 2]
```diff
@@ -189,6 +189,51 @@ func TestSnapshotFSChangePermissions(t *testing.T) {
...
+
+	// Expect "bar", which used to be a non-empty directory but now is a symlink. We don't want whiteout files for
+	// the deleted files in bar, because without a parent directory for them the tar cannot be extracted.
+	testDirWithoutLeadingSlash := strings.TrimLeft(testDir, "/")
+	expectedFiles := []string{
+		filepath.Join(testDirWithoutLeadingSlash, "bar"),
+		filepath.Join(testDirWithoutLeadingSlash, "foo"),
+	}
+	for _, path := range util.ParentDirectoriesWithoutLeadingSlash(filepath.Join(testDir, "foo")) {
+		expectedFiles = append(expectedFiles, strings.TrimRight(path, "/")+"/")
```
Comment (gabyx) [inline pkg/snapshot/snapshot_test.go:229]: `strings.TrimRight(path, "/")+"/" `isnt the same as `path + "/" `??

**Review by gabyx — APPROVED** [review]
Looks good to me.
Some questions, and small typos I guess.

File: pkg/snapshot/snapshot.go (hunk 1 above)
Comment (aaron-prindle) [reply pkg/snapshot/snapshot.go:267]: +1

File: pkg/snapshot/snapshot_test.go (hunk 2 above)
Comment (aaron-prindle) [reply pkg/snapshot/snapshot_test.go:229]: I think in this case `path + "/"` is going to be identical but `TrimRight` also removes whitespace characters from from the right of the element IIUC.  Not sure if the test needs whitespace removal but this line of code is already used in the test currently:
https://github.com/GoogleContainerTools/kaniko/blob/main/pkg/snapshot/snapshot_test.go#L219

so likely fine either way

**Comment by aaron-prindle** [comment]
Agree w/ @gabyx, LGTM just address the single nit s/err/nil and we should be able to merge! 🎊

File: pkg/snapshot/snapshot.go (hunk 1 above)
Comment (andreasf) [reply pkg/snapshot/snapshot.go]: Oops. Fixed!

File: integration/integration_test.go [hunk 3]
```diff
@@ -896,10 +955,10 @@ func initIntegrationTestConfig() *integrationTestConfig {
 	var gcsEndpoint string
 	var disableGcsAuth bool
 	flag.StringVar(&c.gcsBucket, "bucket", "gs://kaniko-test-bucket", "The gcs bucket argument to uploaded the tar-ed contents of the `integration` dir to.")
-	flag.StringVar(&c.imageRepo, "repo", "gcr.io/kaniko-test", "The (docker) image repo to build and push images to during the test. `gcloud` must be authenticated with this repo or serviceAccount must be set.")
+	flag.StringVar(&c.imageRepo, "repo", "localhost:5000", "The (docker) image repo to build and push images to during the test. `gcloud` must be authenticated with this repo or serviceAccount must be set.")
```
Comment (aaron-prindle) [inline integration/integration_test.go:958]: I missed this initially but can  you also change this back to its original value

File: integration/integration_test.go [hunk 4]
```diff
@@ -896,10 +955,10 @@ func initIntegrationTestConfig() *integrationTestConfig {
...
 	flag.StringVar(&c.serviceAccount, "serviceAccount", "", "The path to the service account push images to GCR and upload/download files to GCS.")
 	flag.StringVar(&gcsEndpoint, "gcs-endpoint", "", "Custom endpoint for GCS. Used for local integration tests")
-	flag.BoolVar(&disableGcsAuth, "disable-gcs-auth", false, "Disable GCS Authentication. Used for local integration tests")
+	flag.BoolVar(&disableGcsAuth, "disable-gcs-auth", true, "Disable GCS Authentication. Used for local integration tests")
```
Comment (aaron-prindle) [inline integration/integration_test.go:961]: I missed this initially but can you also change this back to its original value

**Review by aaron-prindle — APPROVED** [review]
Thanks for the PR here @andreasf!  LGTM
