### PR TITLE
Fix resolving arguments over multi-stage build

### LINKED ISSUE #1911: Args not resolved in multi-stage build
**Actual behavior**
Accesing `ARG`s in previous stages are not resolved correctly.

**Expected behavior**
They should be resolved.

**To Reproduce**

```dockerfile
FROM alpine:latest as base
RUN echo hi > /hi

FROM base AS base-dev
ARG NAME="1234"
RUN echo "dev:: $NAME" >> /hi

FROM base-dev as base-custom
ARG NAME
RUN echo "custom:: $NAME"
RUN cat /hi
 ```

Build **without** specifying `--build-arg="..."`.

**Result**:  `custom:: `. (`$NAME` is empty) but should be `1234`)

 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by gabyx**
Fixes #1911

**Description**

Arguments are not correctly resolved over multi-stage builds.
See test.

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [x] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

- Arguments over multi-stage builds are transiently propagated which was not working before.

### CODE REVIEW

**Comment by gabyx** [comment]
I added a test, but how do I provide the reference data? Thanks

File: pkg/executor/build.go [hunk 1]
```diff
@@ -142,7 +142,11 @@ func newStageBuilder(opts *config.KanikoOptions, stage config.KanikoStage, cross
 		s.cmds = append(s.cmds, command)
 	}
 
-	s.args = dockerfile.NewBuildArgs(s.opts.BuildArgs)
+	if args != nil {
+		s.args = args
```
Comment (gabyx) [inline pkg/executor/build.go:146]: I think we should copy here the set as in the else.

**Comment by gabyx** [comment]
The test works:

```
go test ./integration -v --repo localhost:5000 -run TestRun/test_Dockerfile_test_multistage_args_issue_1911
```

**Review by imjasonh — APPROVED** [review]
