### PR TITLE
Fix copying ownership

### LINKED ISSUE #1315: Kaniko not preserving ownership on staging building
**Actual behavior**
Kaniko does not preserving owner and group for directories and files on staging building.

**Expected behavior**
Same owner and group as in parent stage

**To Reproduce**
1. build Dockerfile bellow
2. Check the permissions:
```
/ # ls /myapp/ -lah
total 0      
drwxr-xr-x    1 root     root          14 Jun 12 16:39 .
drwxr-xr-x    1 root     root         144 Jun 12 16:40 ..
drwxr-xr-x    1 root     root           0 Jun 12 16:39 somedir
```

**Additional Information**
 - Dockerfile
```Dockerfile
FROM alpine:3.11 as builder

RUN mkdir -p /myapp/somedir \
 && chown 123:123 /myapp/somedir

FROM alpine:3.11
COPY --from=builder /myapp /myapp
```
 - Build Context
 - Kaniko Image:
```
gcr.io/kaniko-project/executor:debug-v0.16.0 (sha256:552567f5a8bbc5d8d293d3210619edfe5e9ea0a04fbe3bdae6fc04f5051d5e00)
```
 
 **Triage Notes for the Maintainers**
 

 
 | **Description** | **Yes/No** |
 |----------------|---------------|
 | Please check if this a new feature you are proposing        | <ul><li>- [ ] </li></ul>|
 | Please check if the build works in docker but not in kaniko | <ul><li>- [ ] </li></ul>| 
 | Please check if this error is seen when you use `--cache` flag | <ul><li>- [ ] </li></ul>|
 | Please check if your dockerfile is a multistage dockerfile | <ul><li>- [ ] </li></ul>|

### PR DESCRIPTION
**Pull request by kvaps**
Fixes #1315

**Description**

This PR solved two problems:

* First problem is that `uid, gid` overriding by loop in `CopyDir` function:
  https://github.com/GoogleContainerTools/kaniko/blob/3ab2e1d193d7974df496de12c5fe1513248d1994/pkg/util/fs_util.go#L692

* Second problem is that `otiai10Cpy.Copy` is not preserving ownership information. Solved by implementing additional loop for copying ownership information.

It might need rebase after merging https://github.com/GoogleContainerTools/kaniko/pull/1724.
This branch includes both fixes: [`kvaps:fix-copying-root-and-ownership`](https://github.com/kvaps/kaniko/tree/fix-copying-root-and-ownership); compiled docker images:
```
ghcr.io/kvaps/kaniko-executor:v1.6.0-fix
ghcr.io/kvaps/kaniko-executor:v1.6.0-fix-debug
ghcr.io/kvaps/kaniko-warmer:v1.6.0-fix
```

**Submitter Checklist**

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [unit tests](../DEVELOPMENT.md#creating-a-pr)
- [X] Adds integration tests if needed.

_See [the contribution guide](../CONTRIBUTING.md) for more details._

**Reviewer Notes**

- [ ] The code flow looks good. 
- [ ] Unit tests and or integration tests added.

**Release Notes**

Describe any changes here so maintainer can include it in the release notes, or delete this block.

```
- Fix ownership setting for files and directories
```

### CODE REVIEW

**Comment by kvaps** [comment]
PR rebased to `v1.7.0`, new docker images with this change prepared:

```
ghcr.io/kvaps/kaniko-executor:v1.7.0
ghcr.io/kvaps/kaniko-executor:v1.7.0-debug
ghcr.io/kvaps/kaniko-warmer:v1.7.0
```

source code of fork in `master` branch:
https://github.com/kvaps/kaniko/

**Review by imjasonh — APPROVED** [review]

File: pkg/util/fs_util.go [hunk 1]
```diff
@@ -894,7 +894,64 @@ func CopyFileOrSymlink(src string, destDir string, root string) error {
...
+			logrus.Debugf("Not copying ownership for %s, as it's ignored", path)
+			return nil
+		}
+
+		info, err = os.Stat(path)
+		if err != nil {
+			return errors.Wrap(err, "reading ownership")
+		}
+		stat := info.Sys().(*syscall.Stat_t)
+		err = os.Chown(destPath, int(stat.Uid), int(stat.Gid))
```
Comment (imjasonh) [inline pkg/util/fs_util.go:951]: This failed a lint check for ineffective error assignment that wasn't present when you proposed this PR. In https://github.com/GoogleContainerTools/kaniko/pull/1858 I tried just having this return the error, but it leads to a unit test failure:

```
time="2021-12-23T19:27:59Z" level=info msg="Saving file copied/bam.txt for later use"
    util.go:73: chown /tmp/592266814/kaniko/0/bam.txt: no such file or directory
        copying ownership
        github.com/GoogleContainerTools/kaniko/pkg/util.CopyFileOrSymlink
        	/home/runner/work/kaniko/kaniko/pkg/util/fs_util.go:910
        github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild
        	/home/runner/work/kaniko/kaniko/pkg/executor/build.go:680
        github.com/GoogleContainerTools/kaniko/pkg/executor.TestCopyCommand_Multistage.func1
        	/home/runner/work/kaniko/kaniko/pkg/executor/copy_multistage_test.go:47
        testing.tRunner
        	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1259
        runtime.goexit
        	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/asm_amd64.s:1581
        could not save file
        github.com/GoogleContainerTools/kaniko/pkg/executor.DoBuild
        	/home/runner/work/kaniko/kaniko/pkg/executor/build.go:681
        github.com/GoogleContainerTools/kaniko/pkg/executor.TestCopyCommand_Multistage.func1
        	/home/runner/work/kaniko/kaniko/pkg/executor/copy_multistage_test.go:47
        testing.tRunner
        	/opt/hostedtoolcache/go/1.17.5/x64/src/testing/testing.go:1259
        runtime.goexit
        	/opt/hostedtoolcache/go/1.17.5/x64/src/runtime/asm_amd64.s:1581
    copy_multistage_test.go:52: open /tmp/592266814/output: no such file or directory
```

If you can figure out the fix that'd be great, otherwise I may have to revert this change to ensure we can keep the project moving forward. Sorry for the difficulty, we're trying to get the gears moving again.

Comment (kvaps) [reply pkg/util/fs_util.go:951]: I'll take a look

Comment (imjasonh) [reply pkg/util/fs_util.go:951]: I got the test to pass with the change in https://github.com/GoogleContainerTools/kaniko/pull/1858/commits/fe94bcce512cf96497ed57de314404ab6fbe2617 but I'd love to have your feedback on whether that's the right way forward.

Comment (kvaps) [reply pkg/util/fs_util.go:951]: Well, I have similar errors even without merging this PR (just in `v1.7.0` for example)

```

INFO[0000] Using dockerignore file: ../../integration/.dockerignore
--- FAIL: Test_GetFSFromLayers_with_whiteouts_include_whiteout_enabled (0.00s)
    fs_util_test.go:1124: initializing filesystem ignore list: checking filesystem mount paths for ignore list: open /proc/self/mountinfo: no such file or directory
--- FAIL: Test_GetFSFromLayers_with_whiteouts_include_whiteout_disabled (0.00s)
    fs_util_test.go:1228: initializing filesystem ignore list: checking filesystem mount paths for ignore list: open /proc/self/mountinfo: no such file or directory
--- FAIL: Test_GetFSFromLayers_ignorelist (0.00s)
    fs_util_test.go:1319: initializing filesystem ignore list: checking filesystem mount paths for ignore list: open /proc/self/mountinfo: no such file or directory
--- FAIL: Test_GetFSFromLayers (0.00s)
    fs_util_test.go:1445: initializing filesystem ignore list: checking filesystem mount paths for ignore list: open /proc/self/mountinfo: no such file or directory
```

Comment (kvaps) [reply pkg/util/fs_util.go:951]: Ah sorry, it seems problem was in architecture of my new M1 chip.

In x86_64 virtual machine all tests were passed with no problems 🤔

Comment (kvaps) [reply pkg/util/fs_util.go:951]: I think this problem is caused by the fact that kaniko directory is overrided just for this unit test:

https://github.com/GoogleContainerTools/kaniko/blob/7065921aa487f99009e3bace196701946dcaea43/pkg/executor/copy_multistage_test.go#L167-L168

But this path is not actually ignored, thus util.CopyOwnership is trying to chown /tmp/592266814/kaniko/0/bam.txt but this file is actually located in staging directory.

Comment (kvaps) [reply pkg/util/fs_util.go:951]: My guess was wring, the relative path was calculated wrong.
Here is PR which fixes this https://github.com/GoogleContainerTools/kaniko/pull/1859
